name: annotate lines using json file

on: pull_request

permissions:
  checks: write

jobs:
  annotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
        with:
          format: "json"

      - name: Save changed files JSON
        run: |
          echo '${{ steps.changed-files.outputs.added_modified }}' | jq . > changed_files.json
          cat changed_files.json

      # This step is just to simulate the output of gql-lint
      - name: Save gql-lint JSON report
        run: cat lint.json

      - name: Generate annotations JSON
        run: .github/workflows/transform.sh lint.json changed_files.json > annotations.json

      - name: Annotate files
        uses: yuzutech/annotations-action@v0.4.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title: "GraphQL Lint"
          input: "annotations.json"
