name: gsheet.action test
on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v2.1.0
        with:
          spreadsheetId: 1paS5iKVR7JcyVmLe2-ztCBkdpE14oQlieA1Nl6qakOM
    
          # commands: | # list of commands, specified as a valid JSON string
          #   [
          #     { "command": "appendData", "args": { "worksheetTitle": "gha-raw", "minCol": 1, "data": [["A1", "A2", "A3"], ["b1", "b2", "b3"]] }}
          #   ]
          commands: ${{ env.CMDS }}
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: echo "$RESULTS" | jq
