name: Manual trigger for gql_new_deprecated_fields

on:
  workflow_dispatch:
    inputs:
      lint_installer:
        description: "URL of gql-lint installer"
        required: false
        default: "https://raw.githubusercontent.com/sketch-hq/gql-lint/main/install.sh"
      base_branch:
        description: "Base branch"
        required: true
        default: main
      schema_urls:
        description: "Schema URLs to lint. Each url in single quotes, separated by a comma. E.g: 'https://graphql.sketch.cloud/api/graphql','https://payments.prod.sketch.com/payments/graphql'"
        default: "'https://graphql.sketch.cloud/api/graphql','https://payments.prod.sketch.com/payments/graphql','https://capacitor.prod.sketch.com/api/introspection'"
      query_files:
        description: "Paths of query files to lint. Each path in single quotes, separated by a comma. E.g: 'Modules/SketchCloudKit/Source/Resources/SketchQL Queries/SketchQL/**/*.graphql','Modules/SharedEditing/Resources/CapacitorQL/**/*.graphql'"
        required: true
        default: "'./**/*.gql','./**/*.graphql'"
      ignore_files:
        description: "Paths of files to ignore. Each path in single quotes, separated by a comma. E.g: './packages/gql-types/graphql/**/local.*.gql','other/path/**/*.graphql'"
        required: false
        default: ""
      fail_new_deprecations:
        description: "Fail the workflow new deprecations are found"
        required: true
        default: "false"
      annotate_deprecations:
        description: "Annotate the PR with deprecations"
        required: true
        default: "false"

jobs:

  trigger:
    uses: sketch-hq/actions-tests/.github/workflows/gql_new_deprecated_fields.yml@main
    with:
      lint_installer: ${{ github.event.inputs.lint_installer }}
      base_branch: ${{ github.event.inputs.base_branch }}
      schema_urls: ${{ github.event.inputs.schema_urls }}
      query_files: ${{ github.event.inputs.query_files }}
      ignore_files: ${{ github.event.inputs.ignore_files }}
      fail_new_deprecations: ${{ github.event.inputs.fail_new_deprecations }}
      annotate_deprecations: ${{ github.event.inputs.annotate_deprecations }}
    secrets: inherit
  
  holi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Holi"
