name: Manual trigger for gql_new_deprecated_fields

on:
  workflow_dispatch:
    inputs:
      lint_installer:
        description: "URL of gql-lint installer"
        required: false
        type: string
        default: "https://raw.githubusercontent.com/sketch-hq/gql-lint/main/install.sh"
      base_branch:
        description: "Base branch"
        required: true
        type: string
        default: main
      schema_urls:
        description: "Schema URLs to lint, comma separated. E.g: https://graphql.sketch.cloud/api/graphql,https://payments.prod.sketch.com/payments/graphql"
        default: "https://graphql.sketch.cloud/api/graphql,https://payments.prod.sketch.com/payments/graphql,https://capacitor.prod.sketch.com/api/introspection"
      query_files:
        description: "Paths of query files to lint, comma separated. E.g: Modules/SketchCloudKit/Source/Resources/SketchQL Queries/SketchQL/**/*.graphql,Modules/SharedEditing/Resources/CapacitorQL/**/*.graphql"
        required: true
        type: string
        default: "./**/*.gql,./**/*.graphql"
      ignore_files:
        description: "Paths of files to ignore, comma separated. E.g: ./packages/gql-types/graphql/**/local.*.gql,other/path/**/*.graphql"
        required: false
        type: string
        default: ""
      fail_new_deprecations:
        description: "Fail the workflow new deprecations are found"
        required: true
        type: boolean
        default: false
      annotate_deprecations:
        description: "Annotate the PR with deprecations"
        required: true
        type: boolean
        default: false

jobs:
  trigger:
    uses: nestor-sk/actions-tests/.github/workflows/gql_new_deprecated_fields.yml@main
    with:
      lint_installer: ${{ inputs.lint_installer }}
      base_branch: ${{ inputs.base_branch }}
      schema_urls: ${{ inputs.schema_urls }}
      query_files: ${{ inputs.query_files }}
      ignore_files: ${{ inputs.ignore_files }}
      fail_new_deprecations: ${{ inputs.fail_new_deprecations }}
      annotate_deprecations: ${{ inputs.annotate_deprecations }}
    secrets: inherit
