name: Notify of new release

on:
  workflow_dispatch:

jobs:
  notify: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $ {{ secrets.NOTIFY_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/nestor-sk/go-buf/actions/workflows/new_lib.yml/dispatches \
          -d '{"ref":"main"}'