name: PR to other repo on new tag

on:
  workflow_dispatch:
  push:
    tags:        
      - '*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          path: this
      - name: Check out other repo
        uses: actions/checkout@v3
        with:
          repository: nestor-sk/gobuf
          fetch-depth: 0
          ref: main
          path: other
          #this token has to have write access to multiple things: actions, commits and other I can't remember now
          token: ${{ secrets.ACTION_TOKEN_2 }}
          persist-credentials: true #I think this the default value
      - name: Create commit in other
        run: |
          cd other
          git checkout -b web-renderer-${{ github.ref_name }}
          cp ../this/stuff.txt stuff.txt
          git config user.name web-renderer-releaser
          git config user.email nestor@sketch.com
          git add .
          git commit -m "Web web-renderer-releaser release ${{ github.ref_name }}"
          git push origin web-renderer-${{ github.ref_name }}
      # - name: Create PR in other
      #   uses: peter-evans/create-pull-request@v5



