name: PR to other repo on new tag

on:
  workflow_dispatch:
  push:
    tags:        
      - '*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          path: this
      - name: Check out other repo
        uses: actions/checkout@v3
        with:
          repository: nestor-sk/gobuf
          fetch-depth: 0
          ref: main
          path: other
          #this token has to have write access to multiple things: actions, commits and other I can't remember now
          #token: ${{ secrets.ACTION_TOKEN_2 }}
          # persist-credentials: true #I think this the default value
      - name: Modify other repo
        run: |
          cp this/stuff.txt other/stuff.txt
      - name: Create PR in other repo
        uses: peter-evans/create-pull-request@v5
        with:
          path: other
          token: ${{ secrets.ACTION_TOKEN_2 }}
          commit-message: "Web web-renderer release ${{ github.ref_name }}"
          title: "Web web-renderer release ${{ github.ref_name }}"
          branch: web-renderer-${{ github.ref_name }}
          base: main




