name: PR to other repo on new tag

on:
  workflow_dispatch:
  push:
    tags:        
      - '*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
        with:
          path: this
      - name: Check out other repo
        uses: actions/checkout@v3
        with:
          repository: nestor-sk/gobuf
          fetch-depth: 0
          ref: main
          path: other
          token: ${{ secrets.ACTION_TOKEN }}
          persist-credentials: true
      - name: Create commit in other
        run: |
          cd other
          git checkout -b new-web-renderer-release
          cp ../this/stuff.txt stuff.txt
          git config user.name web-renderer-releaser
          git config user.email nestor@sketch.com
          git add .
          git commit -m "New web renderer release"
          git push origin new-web-renderer-release
      # - name: Create PR in other
      #   uses: peter-evans/create-pull-request@v5



