name: One taking a number and a JSON as input

on:
  workflow_dispatch:
    inputs:
      number:
        description: "The number"
        required: true
        default: "0"
      report:
        description: "Stringified JSON"
        required: true

jobs:
  lint-deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: Read input and display
        run: |
          echo "Number of deprecated fields: ${{ github.event.inputs.number }}"
          echo "Report as comes: ${{ github.event.inputs.report }}"
          echo "Report with fromJSON: ${{ fromJSON(github.event.inputs.report) }}"
          echo "Report with fromJSON-toJSON: ${{ toJSON(fromJSON(github.event.inputs.report)) }}"
          echo "${{ github.event.inputs.report }}" > report.json

      - name: Display report.json
        run: |
          cat report.json
